# Docker build arguments
ARG NODEJS_VERSION=20

FROM node:${NODEJS_VERSION}-alpine

COPY . /app

ARG SOURCE_DIR=/app
WORKDIR ${SOURCE_DIR}

RUN npm install --global pnpm

RUN pnpm install

CMD pnpm dev
