blank_issues_enabled: false
contact_links:
  - name: 💬 Support via Discord
    url: https://discord.gg/ckbvBtDJgC
    about: Chat with other users and the Seerr dev team
  - name: 💬 Support via GitHub Discussions
    url: https://github.com/seerr-team/seerr/discussions
    about: Ask questions and discuss with other community members
